version: "3"
services:
    # start the ganache cli container
    ganache-cli:
        container_name: ganache
        build:
            context: ./ganache
        # note host:container
        ports:
            - 5545:8545
    truffle_suite:
        container_name: truffle_dev
        build:
            context: ./truffle-dev
                # volumes
        volumes:
            - ".:/workspace"
        # command: >
        #     bash
        stdin_open: true # docker run -i
        tty: true # docker run -t
